'use client';
import {useEffect,useState,useCallback} from 'react';
import {BrainCircuit,ArrowUpRight,Check,Plus,History,RefreshCw,Pause,Play,Database,Zap,MessageSquare,BookOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {api,useMemory} from './agent-state';
import type {MemoryRecord,AgentRun} from '@/lib/agent/types';
export type AgentStatus={configured:boolean;model:string;marketConfigured:boolean;schedulerConfigured:boolean;runs:AgentRun[];budget:{reserved:number;calls:number};usage:{inputTokens:number;outputTokens:number;cachedTokens:number};limit:number};
type Event={id:string;ticker:string;body:string;status:string;createdAt:string};
type Monitor={events:Event[];check:null|{checkedAt:string;status:string;detail:string}};
export function SourceText({text}:{text:string}){const parts=text.split(/(https:\/\/[^\s<>]+)/g);return <div className="answer-text">{parts.map((s,i)=>s.startsWith('https://')?<a key={i} href={s.replace(/[).,\]]+$/,'')} target="_blank" rel="noopener noreferrer">{s}</a>:s)}</div>}
export default function AgentDesk({onAsk}:{onAsk:(question:string,ticker?:string,threadId?:string)=>void}){
 const {records,loading,error,save,refresh}=useMemory();const [status,setStatus]=useState<AgentStatus|null>(null),[monitor,setMonitor]=useState<Monitor>({events:[],check:null}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('investigations');
 const [editing,setEditing]=useState<MemoryRecord|null>(null),[form,setForm]=useState(false),[kind,setKind]=useState('intent'),[ticker,setTicker]=useState('PORTFOLIO'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[recordStatus,setRecordStatus]=useState('draft'),[url,setUrl]=useState(''),[ruleType,setRuleType]=useState('daily_move'),[threshold,setThreshold]=useState('5'),[reviewAt,setReviewAt]=useState(''),[versions,setVersions]=useState<MemoryRecord[]|null>(null);
 const reload=useCallback(async()=>{try{const [a,m]=await Promise.all([api<AgentStatus>('/api/assistant'),api<Monitor>('/api/monitor')]);setStatus(a);setMonitor(m);}catch(e){setNotice(e instanceof Error?e.message:'Agent data unavailable.');}},[]);useEffect(()=>{void reload();},[reload]);
 const openForm=(type:string,r?:MemoryRecord)=>{setEditing(r||null);setKind(type);setTicker(r?.ticker||'PORTFOLIO');setTitle(r?.title||'');setBody(r?.body||'');setRecordStatus(r?.status||(type==='rule'?'active':'draft'));setUrl(String(r?.payload.url||''));setRuleType(String(r?.payload.type||'daily_move'));setThreshold(String(r?.payload.threshold??5));setReviewAt(r?.payload.reviewAt?String(r.payload.reviewAt).slice(0,16):'');setNotice('');setForm(true);};
 async function submit(){setBusy(true);try{const payload=kind==='evidence'?{url}:kind==='rule'?(ruleType==='review_date'?{type:ruleType,reviewAt:new Date(reviewAt+'Z').toISOString()}:{type:ruleType,threshold:Number(threshold)}):editing?.payload||{};await save({id:editing?.id||crypto.randomUUID(),expectedVersion:editing?.version||0,kind:kind as 'intent',ticker,title,body,status:recordStatus as 'draft',payload});setForm(false);setNotice('Saved with version history.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function changeStatus(r:MemoryRecord,next:string){setBusy(true);try{await save({expectedVersion:r.version,status:next as 'accepted',id:r.id,kind:r.kind,ticker:r.ticker,title:r.title,body:r.body,payload:r.payload});setNotice('Updated. Previous versions are preserved.');}catch(e){setNotice(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 async function check(){setBusy(true);try{setMonitor(await api<Monitor>('/api/monitor',{}));await reload();setNotice('Checks completed without an LLM call.');}catch(e){setNotice(e instanceof Error?e.message:'Check failed.');}finally{setBusy(false);}}
 return <div className="agent-desk"><div className="page-heading"><div><p className="eyebrow">CONTINUITY / EVIDENCE / INTENT</p><h1>Agent desk<span className="heading-dot">.</span></h1></div><button className="primary-button" onClick={()=>onAsk('Review my saved intent, notes, and scenarios. What needs my attention?','PORTFOLIO')}><MessageSquare size={16}/> Ask Bastion</button></div>
 <div className="agent-overview"><div><BrainCircuit size={22}/><span>Reasoning</span><strong>{status?(status.configured?'Connected':'Connection needed'):'Loading…'}</strong><small>{status?.configured?status.model:'OpenAI API key required'}</small></div><div><Database size={22}/><span>Persistent memory</span><strong>{loading?'Loading…':error?'Unavailable':`${records.length} records`}</strong><small>Intent, scenarios, evidence, checkpoints</small></div><div><Zap size={22}/><span>AI usage today</span><strong>{status?`${((status.usage?.inputTokens||0)+(status.usage?.outputTokens||0)).toLocaleString()} tokens`:'—'}</strong><small>{status?.budget.calls||0} requests · {(status?.usage?.cachedTokens||0).toLocaleString()} cached input</small></div></div>
 {error&&<div className="agent-notice" role="alert">{error} <button onClick={refresh}>Retry memory</button></div>}{notice&&<p className="agent-notice" role="status">{notice}</p>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="agent-tabs"><TabsTrigger value="investigations">Investigations</TabsTrigger><TabsTrigger value="memory">Memory & intent</TabsTrigger><TabsTrigger value="monitoring">Monitoring</TabsTrigger><TabsTrigger value="operations">Connections & usage</TabsTrigger></TabsList>
 <TabsContent value="investigations"><div className="agent-section-head"><h2>Continue the work</h2><button className="text-button" onClick={reload}><RefreshCw size={14}/> Refresh</button></div>{!status?.runs.length?<div className="agent-empty"><BrainCircuit size={30}/><h3>A research partner with a record.</h3><p>Ask about a holding or save your investment intent. Investigations will retain the question, evidence supplied, actions, and next steps.</p><button className="text-button" onClick={()=>openForm('intent')}>Set your investment intent <ArrowUpRight size={15}/></button></div>:status.runs.map(r=><article className="memory-card" key={r.id}><div className="memory-meta"><span>{r.ticker}</span><span>{r.status} · {new Date(r.createdAt).toLocaleString()}</span></div><h3>{r.question}</h3><SourceText text={r.answer||'Investigation is still running. Refresh to check its progress.'}/><div className="memory-actions"><button className="text-button" onClick={()=>onAsk('Continue this investigation. Check what changed and identify the next unresolved question.',r.ticker,r.threadId)}>Continue investigation <ArrowUpRight size={15}/></button><details><summary>Context supplied</summary><pre>{JSON.stringify(r.manifest,null,2)}</pre></details></div></article>)}</TabsContent>
 <TabsContent value="memory"><div className="agent-section-head"><h2>Your durable record</h2><div className="memory-actions"><button className="text-button" onClick={()=>openForm('intent')}><Plus size={15}/> Intent</button><button className="text-button" onClick={()=>openForm('evidence')}><Plus size={15}/> Evidence</button><button className="text-button" onClick={()=>openForm('investigation')}><Plus size={15}/> Checkpoint</button></div></div><p className="muted">Accepted intent guides the assistant. Exploratory scenarios remain separate. Original journal entries are also retrieved when relevant.</p>{!records.filter(r=>r.kind!=='rule').length&&<div className="agent-empty"><BookOpen size={30}/><h3>Start with what matters to you.</h3><p>Record your horizon, the reason behind a position, or the evidence that would change your mind.</p></div>}{records.filter(r=>r.kind!=='rule').map(r=><article className="memory-card" key={r.id}><div className="memory-meta"><span>{r.ticker} / {r.kind}</span><span>{r.status} · version {r.version}</span></div><h3>{r.title}</h3><SourceText text={r.body}/>{r.kind==='scenario'&&<p className="muted">{JSON.stringify(r.payload.inputs)}</p>}{r.kind==='evidence'&&typeof r.payload.url==='string'&&<a className="text-button" href={r.payload.url} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={14}/></a>}<div className="memory-actions">{r.kind!=='scenario'&&<button className="text-button" disabled={busy} onClick={()=>openForm(r.kind,r)}>Edit</button>}{r.status!=='accepted'&&r.kind==='intent'&&<button className="text-button" disabled={busy} onClick={()=>changeStatus(r,'accepted')}><Check size={14}/> Accept intent</button>}{r.status!=='superseded'&&<button className="text-button" disabled={busy} onClick={()=>changeStatus(r,'superseded')}>Archive</button>}<button className="text-button" onClick={async()=>{try{setVersions((await api<{history:MemoryRecord[]}>(`/api/memory?history=${r.id}`)).history);}catch(e){setNotice(String(e));}}}><History size={14}/> History</button></div></article>)}</TabsContent>
 <TabsContent value="monitoring"><div className="agent-section-head"><h2>Signals worth investigating</h2><div className="memory-actions"><button className="text-button" onClick={()=>openForm('rule')}><Plus size={15}/> Add rule</button><button className="primary-button" disabled={busy} onClick={check}>{busy?'Checking…':'Check now'}</button></div></div><div className="agent-notice">Checks run on demand. Unattended monitoring requires an authenticated server scheduler. Price checks require a connected feed; dated reviews work without one.</div>{monitor.check&&<p className="muted">Last check {new Date(monitor.check.checkedAt).toLocaleString()} · {monitor.check.detail}</p>}<div className="monitor-grid"><section><h3>Rules</h3>{!records.some(r=>r.kind==='rule')&&<p className="panel-caption">No monitoring rules yet.</p>}{records.filter(r=>r.kind==='rule').map(r=><article className="memory-card" key={r.id}><div className="memory-meta"><span>{r.ticker}</span><span>{r.status}</span></div><h3>{r.title}</h3><p>{String(r.payload.type).replaceAll('_',' ')} · {String(r.payload.threshold??r.payload.reviewAt??'')}</p><div className="memory-actions"><button className="text-button" onClick={()=>openForm('rule',r)}>Edit</button><button className="text-button" disabled={busy} onClick={()=>changeStatus(r,r.status==='active'?'paused':'active')}>{r.status==='active'?<Pause size={14}/>:<Play size={14}/>} {r.status==='active'?'Pause':'Resume'}</button></div></article>)}</section><section><h3>Review queue</h3>{!monitor.events.length&&<p className="panel-caption">Triggered rules appear here. Duplicate signals are grouped per rule and day.</p>}{monitor.events.map(e=><article className="memory-card" key={e.id}><div className="memory-meta"><span>{e.ticker}</span><span>{e.status}</span></div><p>{e.body}</p><div className="memory-actions"><button className="text-button" onClick={()=>onAsk(`Investigate this signal. Separate evidence from possible explanations: ${e.body}`,e.ticker)}>Investigate <ArrowUpRight size={15}/></button>{e.status!=='dismissed'&&<button className="text-button" onClick={async()=>{try{await api('/api/monitor',{dismiss:e.id});await reload();}catch(e){setNotice(String(e));}}}>Dismiss</button>}</div></article>)}</section></div></TabsContent>
 <TabsContent value="operations"><div className="panel"><h2>Connections</h2><dl className="facts"><div><dt>Model API</dt><dd>{status?.configured?'Connected':'OPENAI_API_KEY needed'}</dd></div><div><dt>Market feed & news</dt><dd>{status?.marketConfigured?'Configured':'FINNHUB_API_KEY needed'}</dd></div><div><dt>Brokerage</dt><dd>Not connected · demo holdings</dd></div><div><dt>Scheduled checks</dt><dd>External scheduler setup required</dd></div></dl><p>Credentials belong in the site's server settings. Never paste a key or brokerage password into the assistant.</p></div><div className="panel"><h2>Token governor</h2><dl className="facts"><div><dt>Daily per-user allowance</dt><dd>{status?.limit.toLocaleString()||'—'} tokens</dd></div><div><dt>Used / reserved allowance</dt><dd>{status?.budget.reserved.toLocaleString()||0}</dd></div><div><dt>Input / output today</dt><dd>{status?.usage?.inputTokens||0} / {status?.usage?.outputTokens||0}</dd></div><div><dt>Tool limit per investigation</dt><dd>3</dd></div><div><dt>Energy and dollar cost</dt><dd>Not measured</dd></div></dl><p>Unknown provider outcomes retain their reservation until the daily reset. Context is compiled for each question; full chat history is not repeatedly appended.</p></div></TabsContent></Tabs>
 <Dialog open={form} onOpenChange={setForm}><DialogContent className="memory-dialog"><DialogTitle>{editing?'Edit':'New'} {kind}</DialogTitle><DialogDescription>Keep your original wording. Saving a correction preserves the earlier version.</DialogDescription><form onSubmit={e=>{e.preventDefault();void submit();}}><div className="memory-form-row"><label>Security<input required disabled={!!editing} value={ticker} maxLength={24} onChange={e=>setTicker(e.target.value.toUpperCase())}/></label><label>Status<select value={recordStatus} onChange={e=>setRecordStatus(e.target.value)}>{(kind==='rule'?['active','paused']:['draft','exploratory','accepted','completed','superseded']).map(s=><option key={s}>{s}</option>)}</select></label></div><label>Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Original reasoning<textarea value={body} maxLength={6000} rows={5} onChange={e=>setBody(e.target.value)}/></label>{kind==='evidence'&&<label>Source URL<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label>}{kind==='rule'&&<div className="memory-form-row"><label>Trigger<select value={ruleType} onChange={e=>setRuleType(e.target.value)}><option value="daily_move">Absolute daily move (%)</option><option value="price_above">Price at or above ($)</option><option value="price_below">Price at or below ($)</option><option value="review_date">Review date</option></select></label>{ruleType==='review_date'?<label>Review time (UTC)<input required type="datetime-local" value={reviewAt} onChange={e=>setReviewAt(e.target.value)}/></label>:<label>Threshold<input required type="number" min="0" step="any" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label>}</div>}<p role="status">{notice}</p><button className="primary-button" disabled={busy}>{busy?'Saving…':'Save record'}</button></form></DialogContent></Dialog>
 <Dialog open={!!versions} onOpenChange={v=>{if(!v)setVersions(null);}}><DialogContent className="memory-dialog"><DialogTitle>Version history</DialogTitle><DialogDescription>Previous wording remains available after a correction.</DialogDescription>{versions?.map(r=><article className="memory-card" key={r.version}><div className="memory-meta"><span>Version {r.version} / {r.status}</span><span>{r.actor} · {new Date(r.createdAt).toLocaleString()}</span></div><h3>{r.title}</h3><SourceText text={r.body}/><pre>{JSON.stringify(r.payload,null,2)}</pre></article>)}</DialogContent></Dialog>
 </div>;
}
