'use client';
import {useState,useEffect,useRef} from 'react';
import {Send,Plus,BrainCircuit,ArrowUpRight,LoaderCircle} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {api,useMemory} from './agent-state';
import {SourceText,type AgentStatus} from './agent-desk';
import type {Focus,UIAction,AgentRun} from '@/lib/agent/types';
export default function AssistantPanel({open,onOpenChange,focus,seed,onAction}:{open:boolean;onOpenChange:(v:boolean)=>void;focus:Focus;seed:{question:string;threadId?:string;nonce:number}|null;onAction:(a:UIAction)=>void}){
 const {refresh}=useMemory();const [text,setText]=useState(''),[status,setStatus]=useState<AgentStatus|null>(null),[thread,setThread]=useState(''),[items,setItems]=useState<AgentRun[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(''),[deferredUI,setDeferredUI]=useState<UIAction[]>([]);const requestId=useRef<string|null>(null);const focusRef=useRef(focus);focusRef.current=focus;const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;let cancelled=false;void api<AgentStatus>('/api/assistant').then(a=>{if(cancelled)return;setStatus(a);const t=seed?.threadId||thread||a.runs[0]?.threadId||crypto.randomUUID();setThread(t);setItems(a.runs.filter(r=>r.threadId===t).reverse());}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[open,seed?.nonce]);
 useEffect(()=>{if(seed){setText(seed.question);requestId.current=null;}},[seed]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[items,pending]);
 async function send(){if(!text.trim()||busy||!status?.configured)return;const captured={...focus};const q=text.trim();const t=thread||crypto.randomUUID();setThread(t);requestId.current??=crypto.randomUUID();setBusy(true);setError('');setPending(q);
 try{const result=await api<{id:string;answer:string;status:string;ui?:UIAction[];manifest:Record<string,unknown>;actions:unknown[];replayed?:boolean}>('/api/assistant',{id:requestId.current,threadId:t,question:q,focus:captured});if(result.status==='running'){setError('This request is still running. Use Refresh conversation to check its result.');return;}if(result.status!=='completed'&&result.status!=='stale')throw new Error(result.answer||'The investigation did not complete. Start a new request to retry.');
 setText('');requestId.current=null;const a=await api<AgentStatus>(`/api/assistant?thread=${t}`);setStatus(a);setItems(a.runs.reverse());await refresh();window.dispatchEvent(new Event('bastion-records-changed'));
 if(result.ui?.length){if(JSON.stringify(focusRef.current)===JSON.stringify(captured)){result.ui.forEach(onAction);}else setDeferredUI(result.ui);}
 }catch(e){setError(e instanceof Error?e.message:'Request failed. Your question is preserved.');}finally{setBusy(false);setPending('');}}
 async function reload(){try{const a=await api<AgentStatus>(`/api/assistant${thread?`?thread=${thread}`:''}`);setStatus(a);setItems(a.runs.reverse());setError('');}catch(e){setError(String(e));}}
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="assistant-sheet"><SheetHeader><div className="assistant-title"><BrainCircuit size={23}/><SheetTitle>Ask Bastion</SheetTitle></div><SheetDescription>{focus.ticker} · {focus.view}{focus.scenario?' · exploratory inputs':''}</SheetDescription></SheetHeader><div className="assistant-toolbar"><span>{status?.configured?'Connected · bounded context':'Model connection needed'}</span><button className="text-button" disabled={busy} onClick={()=>{setThread(crypto.randomUUID());setItems([]);setText('');setError('');requestId.current=null;}}><Plus size={14}/> New thread</button></div>
 <div className="assistant-messages">{!items.length&&<div className="assistant-welcome"><span className="assistant-emblem"><BrainCircuit size={28}/></span><h2>Keep the whole decision in view.</h2><p>Discuss a holding, test a scenario, or ask me to change this workspace. Your saved intent and relevant research come with the conversation.</p><div className="assistant-prompts">{['What changed in my investment thesis?','Compare the portfolio with its benchmark.','Create a lower-case LUMN scenario using the current inputs.'].map(q=><button key={q} onClick={()=>{setText(q);requestId.current=null;}}>{q}<ArrowUpRight size={15}/></button>)}</div>{!status?.configured&&<p className="agent-notice">An OpenAI API key is required in server settings to enable answers and conversational actions. No AI calls are being made.</p>}</div>}
 {items.map(r=><article className="conversation-turn" key={r.id}><div className="user-message">{r.question}</div><div className="assistant-message"><span className="eyebrow">BASTION / {r.status}</span><SourceText text={r.answer||'Working…'}/>{r.actions.length>0&&<details><summary>{r.actions.length} tool results</summary><pre>{JSON.stringify(r.actions,null,2)}</pre></details>}<details><summary>Memory used for this answer</summary><pre>{JSON.stringify(r.manifest,null,2)}</pre></details></div></article>)}{pending&&<div className="conversation-turn"><div className="user-message">{pending}</div><p className="assistant-working"><LoaderCircle className="spin" size={17}/> Gathering context and working…</p></div>}<div ref={end}/></div>
 {deferredUI.length>0&&<div className="agent-notice">You changed views while I worked. <button onClick={()=>{deferredUI.forEach(onAction);setDeferredUI([]);}}>Apply requested view changes</button></div>}{error&&<div className="agent-notice" role="alert">{error}<br/><button disabled={busy} onClick={()=>{requestId.current=null;setError('Ready for a new request. Check previous tool results before repeating a change.');}}>Start a new request</button></div>}
 <form className="assistant-composer" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="assistant-question">Ask Bastion</label><textarea id="assistant-question" value={text} maxLength={4000} rows={3} placeholder="Ask about this holding or change your workspace…" onChange={e=>{setText(e.target.value);requestId.current=null;}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div><button type="button" className="text-button" disabled={busy} onClick={reload}>Refresh conversation</button><button className="primary-button" disabled={busy||!text.trim()||!status?.configured}>{busy?'Working…':'Send'}<Send size={15}/></button></div><p>Enter to send · Shift + Enter for a new line. Portfolio values remain demo data.</p></form></SheetContent></Sheet>;
}
