'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ResearchActivity} from './research-activity';
import {Search,RefreshCw,ExternalLink,Download,Upload,Link2,Square,FileText,ArrowRight} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {safeSourceUrl} from '@/lib/research/schema.mjs';
import type {Report,Run,Metric,Evidence} from '@/lib/research/types';

type Status={account:{connected:boolean;email:string|null};login?:{authUrl?:string;error?:string}|null;activeRuns:string[]};
type Detail={title:string;text:string;evidence:Evidence;metric?:Metric};
const fmt=(n:number|null,unit='')=>n===null?'Not disclosed':`${new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n)}${unit?' '+unit:''}`;
async function api<T=Run>(path:string,body?:unknown):Promise<T>{const r=await fetch('/research-api'+path,{method:body===undefined?'GET':'POST',headers:{'X-Bastion-Client':'research-v1',...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('Open Bastion with the local launcher to use company research.');const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||'Research service unavailable');return data;}
export default function ResearchDesk({ticker:initialTicker,onTicker,onJournal}:{ticker:string;onTicker:(ticker:string)=>void;onJournal:(ticker:string,text:string)=>void}){
  const [ticker,setTicker]=useState(initialTicker),[focus,setFocus]=useState(''),[status,setStatus]=useState<Status|null>(null),[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState<Run|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[period,setPeriod]=useState('annual'),[detail,setDetail]=useState<Detail|null>(null),[question,setQuestion]=useState(''),[followup,setFollowup]=useState<Run|null>(null);
  const [checkedAt,setCheckedAt]=useState(0),[offline,setOffline]=useState(false);
  const fileRef=useRef<HTMLInputElement>(null),selection=useRef(0);const report=selected?.report;
  const reload=useCallback(async()=>{try{const s=await api<Status>('/status');setCheckedAt(Date.now());setOffline(false);setStatus(s);const r=await api<{runs:Run[]}>('/runs');setRuns(r.runs);return r.runs as Run[];}catch(e){setOffline(true);throw e;}},[]);
  useEffect(()=>{setTicker(initialTicker);},[initialTicker]);
  useEffect(()=>{let live=true;void reload().then(async list=>{const candidate=list.find(r=>r.status==='running')||list.find(r=>(r as Run&{hasReport?:boolean}).hasReport);if(candidate){const r=await api('/runs/'+candidate.id);if(live)setSelected(r);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[reload]);
  useEffect(()=>{const timer=setInterval(()=>{void reload().then(async()=>{if(selected&&['running','queued'].includes(selected.status)){const r=await api('/runs/'+selected.id);setSelected(r);}if(followup&&['running','queued'].includes(followup.status))setFollowup(await api('/runs/'+followup.id));}).catch(e=>setError(e.message));},3000);return()=>clearInterval(timer);},[status!==null,reload,selected?.id,selected?.status,followup?.id,followup?.status]);
  async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Research request failed');}finally{setBusy(false);}}
  async function openRun(id:string){const seq=++selection.current;await action(async()=>{const r=await api('/runs/'+id);if(seq!==selection.current)return;if(r.parentRunId){setFollowup(r);setSelected(await api('/runs/'+r.parentRunId));}else{setSelected(r);setFollowup(null);}setTicker(r.ticker);onTicker(r.ticker);});}
  async function start(follow=false){await action(async()=>{const symbol=follow?selected!.ticker:ticker.trim().toUpperCase();const r=await api('/runs',{id:crypto.randomUUID(),ticker:symbol,question:follow?question:focus,...(follow?{parentRunId:selected!.id}:{})});if(follow){setFollowup(r);setQuestion('');}else{setSelected(r);setFollowup(null);onTicker(symbol);setTab('overview');}await reload();});}
  async function connect(){await action(async()=>{const r=await api<Status>('/connect',{});await reload();if(!r.account.connected){await api('/login',{});await reload();}});}
  function exportReport(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`bastion-${report.company.ticker}-${report.asOf}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const evidence=(row:Evidence,title:string,text='',metric?:Metric)=><button className="rd-evidence" onClick={()=>setDetail({title,text,evidence:row,metric})}>{row.sourceIds.length?`${row.sourceIds.length} source${row.sourceIds.length===1?'':'s'}`:'Evidence missing'} <ArrowRight size={13}/></button>;
  const running=selected&&['running','queued'].includes(selected.status);
  return <section className="research-desk"><div className="page-heading"><div><p className="eyebrow">COMPANY INTELLIGENCE</p><h1>Research desk<span className="heading-dot">.</span></h1></div><span className="badge">{status&&!offline?(status.account.connected?'CHATGPT SIGNED IN':'LOCAL SERVICE READY'):'LOCAL SERVICE OFFLINE'}</span></div>
  <div className="rd-controls"><form onSubmit={e=>{e.preventDefault();void start();}} className="rd-search"><label htmlFor="rd-ticker">Company ticker</label><div><Search size={18}/><input id="rd-ticker" value={ticker} maxLength={28} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="NYSE:ORN" required/><button className="primary-button" disabled={busy||!status?.account.connected||!!status.activeRuns.length}><Search size={15}/> Research company</button></div></form><button className="text-button" onClick={connect} disabled={busy||!status}><Link2 size={16}/>{status?.account.connected?'Check sign-in':'Connect ChatGPT'}</button><button className="icon-button" aria-label="Reconnect local service" disabled={busy} onClick={()=>action(async()=>{await reload();})}><RefreshCw size={16}/></button></div>
  <label className="rd-focus">Research focus <span className="muted">Optional</span><input value={focus} onChange={e=>setFocus(e.target.value)} maxLength={6000} placeholder="For example: debt refinancing, subsidiary economics, and contract execution"/></label>
  {status?.login?.authUrl&&<p className="rd-notice"><a href={status.login.authUrl} target="_blank" rel="noreferrer">Continue sign-in with ChatGPT <ExternalLink size={14}/></a> Return here after signing in. <button className="text-button" onClick={()=>action(async()=>{await api('/connect',{});await reload();})}>Check sign-in</button></p>}
  {status?.account.connected&&<p className="muted">ChatGPT sign-in is available through Codex. Research availability is confirmed when a request runs successfully.</p>}
  {error&&<p className="rd-error" role="alert">{error}</p>}{status?.login?.error&&<p className="rd-error" role="alert">{status.login.error}</p>}
  {!status&&<div className="rd-notice"><strong>Run Bastion on your computer</strong><p>The local research service stores your reports and connects to Codex through your ChatGPT account. Start the project’s local launcher, then open the address it provides.</p></div>}
  <div className="rd-layout"><aside className="rd-history"><div className="section-title"><h2>Saved research</h2><span className="count">{runs.length}</span></div>{!runs.length&&<p className="muted">Your company reports and follow-ups will appear here.</p>}{runs.map(r=><button key={r.id} className={`rd-history-item ${selected?.id===r.id||followup?.id===r.id?'selected':''}`} onClick={()=>openRun(r.id)}><strong>{r.ticker}</strong><span>{r.parentRunId?'Follow-up':r.question==='Imported report'?'Imported report':'Company report'}</span><small>{new Date(r.createdAt).toLocaleDateString()} · {r.status}</small></button>)}<button className="text-button" disabled={!status||busy} onClick={()=>fileRef.current?.click()}><Upload size={14}/> Import report</button><input type="file" accept="application/json,.json" hidden ref={fileRef} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void action(async()=>{if(file.size>4*1024*1024)throw new Error('Report exceeds 4 MB');const r=await api('/import',JSON.parse(await file.text()));setSelected(r);setFollowup(null);await reload();});}}/></aside>
  <div className="rd-main">{selected&&<ResearchActivity run={followup||selected} checkedAt={checkedAt} offline={offline}/>}{selected&&!report&&<div className="rd-run panel" role="status"><p className="eyebrow">{selected.ticker} / {selected.status}</p><h2>{selected.stage}</h2><p>{selected.error||'Research continues if you leave this tab. The completed report will be saved locally.'}</p>{running&&<button className="text-button" onClick={()=>action(async()=>{await api('/runs/'+selected.id+'/cancel',{});setSelected(await api('/runs/'+selected.id));await reload();})}><Square size={14}/> Cancel research</button>}</div>}
  {!selected&&<div className="rd-empty"><FileText size={30}/><h2>Understand the whole company.</h2><p>Enter a ticker to investigate how it earns revenue, what its subsidiaries do, and which operating and financial risks matter.</p><div className="rd-empty-grid"><span>01 / Portfolio & revenue</span><span>02 / Financial statements</span><span>03 / Subsidiaries & contracts</span><span>04 / Risks & evidence</span></div><p className="muted">Each report records its date, sources, and research gaps. Financial values remain separate from assumptions.</p></div>}
  {report&&<><div className="rd-company"><div><p className="eyebrow">{report.company.exchange}: {report.company.ticker} · AS OF {report.asOf}</p><h2>{report.company.name}</h2><p>{report.company.businessModels.join(' · ')}</p></div><button className="text-button" onClick={exportReport}><Download size={15}/> Export</button></div>
  <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="rd-tabs">{[['overview','Overview'],['financials','Financials'],['subsidiaries','Subsidiaries'],['contracts','Contracts'],['risks','Risks & competition'],['terms','Definitions'],['sources','Sources']].map(([v,label])=><TabsTrigger key={v} value={v}>{label}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview"><p className="rd-summary">{report.summary}</p><div className="rd-stat-grid">{report.metrics.filter(m=>m.value!==null).slice(0,6).map(m=><button key={m.id} onClick={()=>setDetail({title:m.label,text:m.definition,evidence:m,metric:m})}><span>{m.label}</span><strong>{fmt(m.value,m.unit)}</strong><small>{m.period} · {m.scope}</small></button>)}</div><div className="section-title"><h2>How revenue is earned</h2></div>{report.revenueTypes.map((r,i)=><article className="rd-section" key={i}><h3>{r.name} <span className="muted">/ {r.segment}</span></h3><p>{r.customerProblem}</p><dl className="rd-facts"><div><dt>Who pays</dt><dd>{r.payer}</dd></div><div><dt>Pricing</dt><dd>{r.pricing}</dd></div><div><dt>Recognition</dt><dd>{r.recognition}</dd></div></dl>{evidence(r,r.name,r.customerProblem)}</article>)}{!report.revenueTypes.length&&<p className="muted">Revenue types were not established in this report.</p>}</TabsContent>
  <TabsContent value="financials"><div className="section-title"><h2>Financial statements</h2><Tabs value={period} onValueChange={setPeriod}><TabsList>{['annual','quarterly','ttm','snapshot'].map(x=><TabsTrigger key={x} value={x}>{x==='ttm'?'TTM':x[0].toUpperCase()+x.slice(1)}</TabsTrigger>)}</TabsList></Tabs></div><div className="rd-table"><Table><TableHeader><TableRow><TableHead>Metric</TableHead><TableHead>Period</TableHead><TableHead className="rd-number">Value</TableHead><TableHead>Scope / basis</TableHead><TableHead>Evidence</TableHead></TableRow></TableHeader><TableBody>{report.metrics.filter(m=>m.periodType===period).map(m=><TableRow key={m.id}><TableCell><button className="text-button" onClick={()=>setDetail({title:m.label,text:m.definition,evidence:m,metric:m})}>{m.label}</button></TableCell><TableCell>{m.period}</TableCell><TableCell className="rd-number">{m.value===null?m.availability.replaceAll('_',' '):fmt(m.value,m.unit)}</TableCell><TableCell>{m.scope}<small className="rd-block">{m.kind}</small></TableCell><TableCell>{evidence(m,m.label,m.definition,m)}</TableCell></TableRow>)}</TableBody></Table></div>{!report.metrics.some(m=>m.periodType===period)&&<p className="muted">No {period} figures were established.</p>}</TabsContent>
  <TabsContent value="subsidiaries"><h2>Operating structure</h2><p className="muted">Legal entities, reporting segments, brands and joint ventures are identified separately.</p>{report.subsidiaries.map(s=><details className="rd-entity" key={s.id}><summary><span><strong>{s.name}</strong><small>{s.entityType.replaceAll('_',' ')}{s.parentId?` · Parent: ${report.subsidiaries.find(p=>p.id===s.parentId)?.name}`:''}</small></span><span>{s.revenue===null?'Revenue not disclosed':fmt(s.revenue,s.revenueUnit)}</span></summary><div><p>{s.role}</p><h3>Day to day</h3><p>{s.dayToDay}</p><dl className="rd-facts"><div><dt>Products / services</dt><dd>{s.products.join('; ')||'Not established'}</dd></div><div><dt>Revenue sources</dt><dd>{s.revenueSources.join('; ')||'Not disclosed'}</dd></div><div><dt>Revenue period</dt><dd>{s.revenuePeriod||'Not disclosed'}</dd></div><div><dt>President / leader</dt><dd>{s.president||'Not verified'}</dd></div><div><dt>Public contact</dt><dd>{s.publicContact||'Not found'}{s.contactUrl&&safeSourceUrl(s.contactUrl)&&<a href={s.contactUrl} target="_blank" rel="noreferrer"> Contact source <ExternalLink size={13}/></a>}</dd></div></dl><p className="muted">{s.disclosureStatus}</p>{evidence(s,s.name,s.role)}</div></details>)}{!report.subsidiaries.length&&<p className="muted">Subsidiary coverage is unavailable. See research limitations.</p>}</TabsContent>
  <TabsContent value="contracts"><h2>Contracts & awards</h2><p className="muted">Publicly discovered awards through {report.coverage.searchedThrough}. Ceilings and options are not guaranteed revenue.</p><div className="rd-table"><Table><TableHeader><TableRow><TableHead>Contract / customer</TableHead><TableHead>Value / basis</TableHead><TableHead>Company share</TableHead><TableHead>Timing</TableHead><TableHead>Evidence</TableHead></TableRow></TableHeader><TableBody>{report.contracts.map(c=><TableRow key={c.id}><TableCell><strong>{c.name}</strong><small className="rd-block">{c.customer}</small><details><summary>Scope & backlog</summary><p>{c.scope}</p><p>{c.backlogTreatment}</p><p>{c.status}</p></details></TableCell><TableCell>{fmt(c.value,c.currency)}<small className="rd-block">{c.valueBasis.replaceAll('_',' ')}</small></TableCell><TableCell>{fmt(c.companyShare,c.currency)}</TableCell><TableCell>{c.awardDate||'Date not disclosed'}<small className="rd-block">{c.duration}</small></TableCell><TableCell>{evidence(c,c.name,c.scope)}</TableCell></TableRow>)}</TableBody></Table></div>{!report.contracts.length&&<p className="muted">No contracts were established in this research scope.</p>}</TabsContent>
  <TabsContent value="risks">{report.claims.map(c=><article className="rd-section" key={c.id}><p className="eyebrow">{c.category.replaceAll('_',' ')} / {c.kind}</p><h3>{c.title}</h3><p>{c.detail}</p><div className="rd-risk-grid"><div><h4>Counterevidence</h4><p>{c.counterEvidence||'Not established'}</p></div><div><h4>What to watch</h4><p>{c.watchMetric||'Not established'}</p></div></div>{evidence(c,c.title,c.detail)}</article>)}{!report.claims.length&&<p className="muted">No supported risk analysis was returned.</p>}</TabsContent>
  <TabsContent value="terms">{report.terms.map((t,i)=><article className="rd-section" key={i}><h3>{t.term}</h3><p>{t.companyDefinition}</p><h4>How the meaning differs</h4><p>{t.industryDifference}</p><h4>Why it matters financially</h4><p>{t.financialImplication}</p>{evidence(t,t.term,t.companyDefinition)}</article>)}{!report.terms.length&&<p className="muted">Company-specific definitions were not established.</p>}</TabsContent>
  <TabsContent value="sources"><h2>Evidence register</h2><p className="muted">Open the document to verify the claim. A citation is not independent verification.</p>{report.sources.map(s=><a key={s.id} className="source-row" href={safeSourceUrl(s.url)||undefined} target="_blank" rel="noreferrer"><FileText size={18}/><div><strong>{s.title}</strong><p>{s.publisher} · {s.sourceType} · Published {s.publishedAt||'date unknown'} · Accessed {s.accessedAt}</p></div><ExternalLink size={15}/></a>)}</TabsContent></Tabs>
  <details className="rd-coverage"><summary>Research coverage · {report.coverage.status}</summary><ul>{[...report.coverage.limitations,...(selected.warnings||[])].map((x,i)=><li key={i}>{x}</li>)}</ul></details>
  <div className="rd-followup"><h2>Ask about this company</h2><p className="muted">Uses this saved report as context. New facts require new evidence.</p><form onSubmit={e=>{e.preventDefault();void start(true);}}><textarea aria-label="Company follow-up question" rows={2} maxLength={6000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would invalidate the investment thesis?"/><button className="primary-button" disabled={busy||!question.trim()||!status?.account.connected||!!status.activeRuns.length}>Ask Bastion <ArrowRight size={14}/></button></form>{followup&&<div className="rd-answer" role="status"><p className="eyebrow">{followup.status}</p><p>{followup.answer||followup.error||followup.stage}</p>{['running','queued'].includes(followup.status)&&<button className="text-button" onClick={()=>action(async()=>{await api('/runs/'+followup.id+'/cancel',{});setFollowup(await api('/runs/'+followup.id));})}>Cancel answer</button>}</div>}<button className="text-button" onClick={()=>onJournal(report.company.ticker,`Company review: ${report.company.name}\nReport as of: ${report.asOf}\n\n${report.summary}\n\nMy thesis:\n\nWhat would change my mind:\n\nSources:\n${report.sources.slice(0,5).map(s=>s.url).join('\n')}`)}>Draft a journal entry from this report <ArrowRight size={14}/></button></div>
  </>}
  </div></div>
  <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="rd-source-sheet"><SheetHeader><SheetTitle>{detail?.title}</SheetTitle><SheetDescription>Definition and supporting evidence</SheetDescription></SheetHeader>{detail&&<div className="rd-source-content"><p>{detail.text}</p>{detail.metric&&<dl className="rd-facts"><div><dt>Value</dt><dd>{fmt(detail.metric.value,detail.metric.unit)}</dd></div><div><dt>Period</dt><dd>{detail.metric.period} / {detail.metric.periodType}</dd></div><div><dt>Scope</dt><dd>{detail.metric.scope}</dd></div><div><dt>Evidence basis</dt><dd>{detail.metric.kind}</dd></div><div><dt>Calculation</dt><dd>{detail.metric.calculation||'Not calculated'}</dd></div></dl>}<h3>Document location</h3><p>{detail.evidence.locator||'No location supplied'}</p>{detail.evidence.sourceIds.map(id=>{const s=report?.sources.find(s=>s.id===id);return s?<a className="source-row" key={id} href={safeSourceUrl(s.url)||undefined} target="_blank" rel="noreferrer"><div><strong>{s.title}</strong><p>{s.publisher} · {s.publishedAt||'Undated'}</p></div><ExternalLink size={14}/></a>:<p key={id}>Source unavailable: {id}</p>;})}</div>}</SheetContent></Sheet>
  </section>;
}
