'use client';
import {useState} from 'react';
import {Bookmark,Check,RotateCcw} from 'lucide-react';
import {useMemory} from './agent-state';
import {scenarioValue,money} from '@/lib/finance';
import type {ScenarioInputs,MemoryRecord} from '@/lib/agent/types';
export default function SavedScenarios({ticker,inputs,onLoad}:{ticker:string;inputs:ScenarioInputs;onLoad:(v:ScenarioInputs)=>void}){const {records,save,error}=useMemory();const [title,setTitle]=useState(''),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState<{id:string;version:number}|null>(null);const saved=records.filter(r=>r.kind==='scenario'&&r.ticker===ticker&&r.status!=='superseded');
 async function create(){setBusy(true);try{const r=await save({id:crypto.randomUUID(),expectedVersion:0,kind:'scenario',ticker,title:title.trim()||`${ticker} scenario`,body:reason,status:'exploratory',payload:{inputs,units:'USD billions; shares billions',model:'EV/EBITDA',value:scenarioValue(inputs.ebitda,inputs.multiple,inputs.debt,inputs.shares),parent:loaded}});setLoaded({id:r.id,version:r.version});setTitle('');setReason('');setNotice('Saved as an exploratory scenario.');}catch(e){setNotice(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 async function accept(r:MemoryRecord){setBusy(true);try{const changed=await save({id:r.id,expectedVersion:r.version,kind:r.kind,ticker:r.ticker,title:r.title,body:r.body,status:r.status==='accepted'?'exploratory':'accepted',payload:r.payload});setNotice(changed.status==='accepted'?'Scenario marked accepted. Other accepted scenarios remain explicit alternatives.':'Returned to exploratory status.');}catch(e){setNotice(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 return <section className="panel saved-scenarios"><div className="section-title"><h2>Scenario memory</h2><span className="badge">EXPLORING</span></div><p>Save this set of assumptions with its reasoning. Moving a slider never changes an accepted record.</p><label>Scenario name<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Lower margin, higher dilution"/></label><label>Why these assumptions?<textarea rows={3} value={reason} maxLength={6000} onChange={e=>setReason(e.target.value)} placeholder="What are you testing, and what evidence would support it?"/></label><button className="primary-button" disabled={busy||!!error} onClick={create}><Bookmark size={15}/>{busy?'Saving…':'Save exploratory scenario'}</button><p className="save-status" role="status">{notice||error}</p>{saved.map(r=><article className="saved-scenario" key={r.id}><div><strong>{r.title}</strong><span>{r.status} · v{r.version} · {money(Number(r.payload.value)||0)}</span></div><div className="memory-actions"><button className="text-button" onClick={()=>{onLoad(r.payload.inputs as ScenarioInputs);setLoaded({id:r.id,version:r.version});setNotice(`Loaded version ${r.version}. Further edits are exploratory.`);}}><RotateCcw size={14}/> Load</button><button className="text-button" disabled={busy} onClick={()=>accept(r)}><Check size={14}/>{r.status==='accepted'?'Make exploratory':'Accept assumptions'}</button></div></article>)}</section>;
}
